// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Velocities.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Velocities.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Velocities::Velocities()
{

    m_linear_velocity_x = 0.0;
    m_linear_velocity_y = 0.0;
    m_angular_velocity_z = 0.0;
}

Velocities::~Velocities()
{
}

Velocities::Velocities(const Velocities &x)
{
    m_robot_id = x.m_robot_id;
    m_linear_velocity_x = x.m_linear_velocity_x;
    m_linear_velocity_y = x.m_linear_velocity_y;
    m_angular_velocity_z = x.m_angular_velocity_z;
}

Velocities::Velocities(Velocities &&x)
{
    m_robot_id = std::move(x.m_robot_id);
    m_linear_velocity_x = x.m_linear_velocity_x;
    m_linear_velocity_y = x.m_linear_velocity_y;
    m_angular_velocity_z = x.m_angular_velocity_z;
}

Velocities& Velocities::operator=(const Velocities &x)
{
    m_robot_id = x.m_robot_id;
    m_linear_velocity_x = x.m_linear_velocity_x;
    m_linear_velocity_y = x.m_linear_velocity_y;
    m_angular_velocity_z = x.m_angular_velocity_z;
    
    return *this;
}

Velocities& Velocities::operator=(Velocities &&x)
{
    m_robot_id = std::move(x.m_robot_id);
    m_linear_velocity_x = x.m_linear_velocity_x;
    m_linear_velocity_y = x.m_linear_velocity_y;
    m_angular_velocity_z = x.m_angular_velocity_z;
    
    return *this;
}

size_t Velocities::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 10 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Velocities::getCdrSerializedSize(const Velocities& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.robot_id().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void Velocities::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    if(m_robot_id.length() <= 10)
    scdr << m_robot_id;
    else
        throw eprosima::fastcdr::exception::BadParamException("robot_id field exceeds the maximum length");
    scdr << m_linear_velocity_x;

    scdr << m_linear_velocity_y;

    scdr << m_angular_velocity_z;

}

void Velocities::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_robot_id;
    dcdr >> m_linear_velocity_x;
    dcdr >> m_linear_velocity_y;
    dcdr >> m_angular_velocity_z;
}

size_t Velocities::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            





    return current_align;
}

bool Velocities::isKeyDefined()
{
    return false;
}

void Velocities::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
	 
	 
	 
}